input.onButtonPressed(Button.A, function () {
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Run, 150)
    basic.pause(1500)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Right, 150)
    basic.pause(800)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Run, 150)
    basic.pause(1500)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Left, 150)
    basic.pause(800)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Run, 150)
    basic.pause(1500)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Right, 150)
    basic.pause(800)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Run, 150)
    basic.pause(1500)
    cbit_小车类.CarCtrlSpeed(cbit_小车类.CarState.Car_Stop, 0)
})
